### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by flowerinthenight** [mobingilabs/pullr-krul#1]
- [ ] Support for handling notifications from Mobingi Docker Registry (dev and prod).
- [ ] Support for handling webhook notification from GitHub.
- [ ] Dispatch GitHub notifications to [pullr-icarium](https://github.com/mobingilabs/pullr-icarium) for autobuilds.
- [ ] Dispatch registry notifications to per-user endpoints (configuration will be in DynamoDB).
- [ ] CI/CD using ECS
